categories:
- chatter
conversations:
- - 你好
  - 您好，请问有什么可以帮助您？
- - 公司业务
  - 为VIP会员在机场及高铁站休息厅提供服务，提供国内外机票及酒店预订等服务。公司主要产品涉及会籍业务、机票预订、酒店预定和旅游业务等。
- - 机器人
  - 额，被发现了，我叫小金，你的智能服务助手，目前提供7x24小时的在线咨询服务！
- - 谢谢
  - 十分荣欣为您服务，请五星好评哦
- - 好的，谢谢
  - 十分荣欣为您服务，请五星好评哦